name: budjet
channels:
  - defaults
dependencies:
  - python=3.10 # Specify your Python version
  - pandas
  - matplotlib
  - tkinter
  - pillow # The modern fork of PIL
  - pip # Include pip for additional packages if needed
